name: Rust

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  build:
    needs: pre-commit
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: crustty-linux-x64
            binary_name: crustty
          - os: ubuntu-24.04-arm
            asset_name: crustty-linux-arm
            binary_name: crustty
          - os: windows-latest
            asset_name: crustty-windows-x64
            binary_name: crustty.exe
          - os: windows-11-arm
            asset_name: crustty-windows-arm
            binary_name: crustty.exe
          - os: macos-latest
            asset_name: crustty-macos-arm
            binary_name: crustty
          - os: macos-15-intel
            asset_name: crustty-macos-x64
            binary_name: crustty

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Archive binary (Windows)
      if: startsWith(matrix.os, 'windows')
      shell: bash
      run: |
        cd target/release
        7z a ${{ matrix.asset_name }}.zip ${{ matrix.binary_name }}
    - name: Archive binary (Unix)
      if: contains(matrix.os, 'windows') == false
      shell: bash
      run: |
        cd target/release
        zip ${{ matrix.asset_name }}.zip ${{ matrix.binary_name }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: target/release/${{ matrix.asset_name }}.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: crustty-*
        path: artifacts
        merge-multiple: true

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*
        generate_release_notes: true
